apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-storage
  namespace: hubble-dev
  labels:
    app: hubble-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubble-storage
  template:
    metadata:
      labels:
        app: hubble-storage
    spec:
      containers:
        - name: storage
          image: cybersecuritybox/hubble-storage:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "120m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - all
          envFrom:
            - secretRef:
                name: hubble-storage